# Generated by Django 4.1.5 on 2023-02-05 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_category_is_active_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['release_date'], name='store_game_release_983286_idx'),
        ),
    ]
