# Generated by Django 4.1.5 on 2023-03-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_comment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField(blank=True, null=True, verbose_name='Url')),
                ('user_name', models.TextField(blank=True, null=True, verbose_name='User')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Date time')),
            ],
        ),
    ]
