# Generated by Django 4.1.5 on 2023-02-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_options_alter_game_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='game_number',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Category games number'),
        ),
    ]
