# Generated by Django 4.1.5 on 2023-02-11 18:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_game_store_game_release_983286_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Game Description'),
        ),
    ]
