# Generated by Django 4.1.5 on 2023-02-19 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_game_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='Comment text')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='Comment publication date')),
                ('rating', models.IntegerField(verbose_name='Comment rating')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.game', verbose_name='Comment game')),
            ],
        ),
    ]
