# Generated by Django 4.1.5 on 2023-01-30 18:22

from django.db import migrations, models
import django.db.models.deletion
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'Game', 'verbose_name_plural': 'Games'},
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Category Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Category is active?'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=30, verbose_name='Category Slug'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Category Title'),
        ),
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.ForeignKey(blank=True, default=store.models.default_category, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='store.category', verbose_name='Game Category'),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(verbose_name='Game Description'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_image',
            field=models.ImageField(blank=True, null=True, upload_to='game', verbose_name='Game Image'),
        ),
        migrations.AlterField(
            model_name='game',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Game is active?'),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Game name'),
        ),
        migrations.AlterField(
            model_name='game',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4, max_length=4, verbose_name='Game Price'),
        ),
        migrations.AlterField(
            model_name='game',
            name='pub_date',
            field=models.DateField(auto_now_add=True, verbose_name='Game pub date'),
        ),
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.DateField(verbose_name='Game release date'),
        ),
        migrations.AlterField(
            model_name='game',
            name='slug',
            field=models.SlugField(max_length=30, verbose_name='Game Slug'),
        ),
    ]
